name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    #CI
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set yml files
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.RDS_HOST }}
          spring.datasource.username: ${{ secrets.RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
          spring.data.redis.host: ${{ secrets.REDIS_HOST }}
          jwt.key: ${{ secrets.JWT_KEY }}
          kakao.api.admin-key: ${{ secrets.KAKAO_ADMIN_KEY }}
          loadbalancer.user: ${{ secrets.LOADBALANCER_USER }}
          loadbalancer.product: ${{ secrets.LOADBALANCER_PRODUCT }}
          aws.access.key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws.secret.key: ${{secrets.AWS_SECRET_ACCESS_KEY}}


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Docker 이미지 빌드
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order .

      # DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/order

      #CD
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo docker stop $(sudo docker ps -q --filter ancestor=jw059/order)
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/order
            sudo docker run -d -e destination=${{ secrets.DESTINATION }} -p 8084:8084 ${{ secrets.DOCKERHUB_USERNAME }}/order
            sudo docker container prune -f
            sudo docker image prune -f
